// frontend/src/routes/download/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { videosApi } from "$lib/api-client";
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Button from "$lib/components/ui/button/index.js";
  import * as Select from "$lib/components/ui/select/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Label } from "$lib/components/ui/label/index.js";
  import { Skeleton } from "$lib/components/ui/skeleton/index.js";
  import type {
    HandlersMetadataRequest,
    ServicesVideoMetadata,
    ServicesVideoOption,
  } from "$api/index";
  import {
    Search,
    Download,
    ArrowLeft,
    Info,
    Youtube,
    FileVideo,
    Clock,
    Type,
    X,
  } from "@lucide/svelte";
  import { Separator } from "$lib/components/ui/separator/index.js";
  import { Switch } from "$lib/components/ui/switch/index.js";

  let url = $state("");
  let customName = $state("");
  let loading = $state(false);
  let metadata: ServicesVideoMetadata | null = $state(null);
  let selectedFormatId = $state<string>("");
  let reEncode = $state(true);
  let error = $state<string | null>(null);
  let searchQuery = $state("");

  const isPlaylist = $derived(url.includes("list="));

  function getResolutionScore(res?: string) {
    if (!res) return 0;
    const parts = res.toLowerCase().split("x");
    if (parts.length === 2) {
      const w = parseInt(parts[0]);
      const h = parseInt(parts[1]);
      return Math.min(w, h) || Math.max(w, h) || 0;
    }
    const match = res.match(/(\d+)/);
    return match ? parseInt(match[0]) : 0;
  }

  const filteredOptions = $derived.by(() => {
    if (!metadata?.options) return [];
    return metadata.options
      .filter((option: ServicesVideoOption) => {
        const isAudioOnly =
          option.vcodec === "none" ||
          (!option.resolution && option.acodec !== "none");
        if (isAudioOnly) return false;

        if (!searchQuery) return true;
        const query = searchQuery.toLowerCase();
        return (
          option.resolution?.toLowerCase().includes(query) ||
          option.extension?.toLowerCase().includes(query) ||
          option.note?.toLowerCase().includes(query)
        );
      })
      .sort((a, b) => {
        const scoreA = getResolutionScore(a.resolution);
        const scoreB = getResolutionScore(b.resolution);
        if (scoreA !== scoreB) return scoreB - scoreA;
        return (b.file_size || 0) - (a.file_size || 0);
      });
  });

  const selectedFormatLabel = $derived.by(() => {
    if (!selectedFormatId) return "Best Quality (Auto)";
    if (!metadata?.options) return "Select a format";
    const option = metadata.options.find(
      (o: ServicesVideoOption) => o.format_id === selectedFormatId,
    );
    if (!option) return "Select a format";
    return `${option.resolution || "Unknown"} - ${option.extension} (${formatFileSize(option.file_size)})`;
  });

  async function checkMetadata() {
    if (!url) return;
    loading = true;
    error = null;
    metadata = null;
    searchQuery = "";
    selectedFormatId = ""; // Reset to auto
    try {
      const req: HandlersMetadataRequest = { url };
      const res = await videosApi.getMetadata(req);
      metadata = res.data;
      if (metadata?.title && !customName) {
        customName = metadata.title;
      } else if (metadata?.title) {
        customName = metadata.title;
      }
    } catch (e: any) {
      console.error(e);
      error = "Failed to fetch metadata. Please check the URL and try again.";
    } finally {
      loading = false;
    }
  }

  async function startDownload() {
    if (!url) return;
    loading = true;
    error = null;
    try {
      await videosApi.createVideo({
        downloadUrl: url,
        formatId: selectedFormatId || undefined,
        name: customName || metadata?.title || "New Download",
        reEncode: reEncode,
      });
      goto("/");
    } catch (e) {
      console.error(e);
      error = "Failed to start download. Please try again.";
      loading = false;
    }
  }

  function formatFileSize(bytes?: number) {
    if (!bytes) return "Unknown size";
    const units = ["B", "KB", "MB", "GB"];
    let size = bytes;
    let i = 0;
    while (size >= 1024 && i < units.length - 1) {
      size /= 1024;
      i++;
    }
    return `${size.toFixed(1)} ${units[i]}`;
  }
</script>

<div
  class="mx-auto space-y-10 animate-in fade-in slide-in-from-bottom-4 duration-700"
>
  <div class="flex flex-col gap-6">
    <div class="flex items-center gap-4">
      <Button.Root
        variant="secondary"
        size="icon"
        href="/"
        class="shrink-0 h-12 w-12 rounded-2xl"
      >
        <ArrowLeft class="h-5 w-5" />
      </Button.Root>
      <h1 class="text-4xl font-extrabold tracking-tight">New Download</h1>
    </div>
    <p class="text-lg text-muted-foreground font-medium leading-relaxed">
      Paste a video link from YouTube, Vimeo, or other supported platforms to
      begin.
    </p>
  </div>

  	  <div class="space-y-6">

  	    <div
  	      class="relative overflow-hidden rounded-[2.5rem] border bg-card p-2 shadow-2xl shadow-primary/5 transition-all focus-within:ring-2 focus-within:ring-primary/20"
  	    >
  	      <div class="flex flex-col gap-2 sm:flex-row">
  	        <div class="relative flex-1">
  	          <Search
  	            class="absolute left-6 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground"
  	          />
  	          <input
  	            type="text"
  	            bind:value={url}
  	            placeholder="Paste URL here..."
  	            class="h-16 w-full rounded-[2rem] border-none bg-transparent pl-14 pr-4 text-lg font-medium focus:outline-none focus:ring-0"
  	            disabled={loading}
  	            onkeydown={(e) =>
  	              e.key === "Enter" &&
  	              (metadata ? startDownload() : checkMetadata())}
  	          />
  	        </div>
  	        <Button.Root
  	          onclick={checkMetadata}
  	          disabled={loading || !url}
  	          variant="secondary"
  	          class="h-16 rounded-[2rem] px-8 text-lg font-bold transition-all hover:scale-[1.02] active:scale-[0.98]"
  	        >
  	          {loading && !metadata ? "Analysing..." : "Fetch Info"}
  	        </Button.Root>
  	      </div>
  	    </div>

  	    {#if isPlaylist}
  	      <div
  	        class="flex items-center gap-3 rounded-2xl bg-amber-500/10 p-4 text-amber-600 border border-amber-500/20 animate-in slide-in-from-top-2 duration-300"
  	      >
  	        <Info class="h-5 w-5 shrink-0" />
  	        <span class="text-sm font-bold"
  	          >Playlist detected. Only the first video will be downloaded.</span
  	        >
  	      </div>
  	    {/if}
  	  </div>

  	

  	  {#if error}

  	    <div

  	      class="flex items-center gap-4 rounded-[2rem] bg-destructive/10 p-6 text-destructive border border-destructive/20 animate-in zoom-in-95 duration-300"

  	    >

  	      <div class="rounded-full bg-destructive/20 p-2">

  	        <Info class="h-6 w-6" />

  	      </div>

  	      <span class="font-bold text-lg">{error}</span>

  	    </div>

  	  {/if}

  	

  	  {#if loading && !metadata}

  	    <div

  	      class="overflow-hidden rounded-[2.5rem] border bg-card p-8 animate-pulse"

  	    >

  	      <div class="flex flex-col gap-8 sm:flex-row">

  	        <div

  	          class="aspect-video w-full rounded-[1.5rem] bg-muted sm:w-72"

  	        ></div>

  	        <div class="flex-1 space-y-4">

  	          <div class="h-8 w-3/4 rounded-full bg-muted"></div>

  	          <div class="space-y-3">

  	            <div class="h-4 w-full rounded-full bg-muted"></div>

  	            <div class="h-4 w-full rounded-full bg-muted"></div>

  	            <div class="h-4 w-2/3 rounded-full bg-muted"></div>

  	          </div>

  	        </div>

  	      </div>

  	    </div>

  	  {/if}

  	

  	  {#if metadata}

  	    <div

  	      class="group relative overflow-hidden rounded-[2.5rem] border bg-card shadow-2xl shadow-primary/5 transition-all animate-in zoom-in-95 slide-in-from-top-4 duration-500"

  	    >

  	      <div class="p-8 space-y-10">

  	        <div class="flex flex-col gap-8 sm:flex-row">

  	          {#if metadata.thumbnail}

  	            <div

  	              class="relative aspect-video w-full shrink-0 overflow-hidden rounded-[1.5rem] border shadow-2xl sm:w-72"

  	            >

  	              <img

  	                src={metadata.thumbnail}

  	                alt={metadata.title}

  	                class="h-full w-full object-cover transition-transform duration-700 group-hover:scale-110"

  	              />

  	            </div>

  	          {/if}

  	            	          <div class="space-y-4 min-w-0">

  	            	            <h3

  	            	              class="text-2xl font-black leading-tight tracking-tight sm:text-3xl line-clamp-2"

  	            	            >

  	            	              {metadata.title}

  	            	            </h3>

  	            <p

  	              class="text-base text-muted-foreground line-clamp-3 leading-relaxed font-medium"

  	            >

  	              {metadata.description}

  	            </p>

  	            <div class="flex flex-wrap gap-3">

  	              <div

  	                class="flex items-center text-sm font-bold bg-muted px-4 py-2 rounded-full"

  	              >

  	                <Clock class="mr-2 h-4 w-4" />

  	                {metadata.duration

  	                  ? (metadata.duration / 60).toFixed(1) + " min"

  	                  : "Unknown"}

  	              </div>

  	              {#if url.includes("youtube.com") || url.includes("youtu.be")}

  	                <div

  	                  class="flex items-center text-sm font-bold bg-red-500/10 text-red-500 px-4 py-2 rounded-full border border-red-500/10"

  	                >

  	                  <Youtube class="mr-2 h-4 w-4" />

  	                  YouTube

  	                </div>

  	              {/if}

  	            </div>

  	          </div>

  	        </div>

  	

  	        <div class="space-y-4">

  	          <div class="flex items-center justify-between px-2">

  	            <Label for="quality" class="text-lg font-bold"

  	              >Override Quality</Label

  	            >

  	            <span

  	              class="text-xs font-bold text-muted-foreground uppercase tracking-widest opacity-60"

  	              >Optional</span

  	            >

  	          </div>

  	          <Select.Root type="single" bind:value={selectedFormatId}>

  	            <Select.Trigger

  	              id="quality"

  	              class="h-16 w-full rounded-[2rem] border-2 bg-muted/30 px-6 text-lg font-bold transition-all hover:bg-muted/50 focus:ring-primary/20"

  	            >

  	              {selectedFormatLabel}

  	            </Select.Trigger>

  	            <Select.Content

  	              class="rounded-[2.5rem] border-2 p-3 shadow-2xl min-w-[320px]"

  	            >

  	              <div class="mb-3 px-2">

  	                <div class="relative">

  	                  <Search

  	                    class="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground opacity-50"

  	                  />

  	                  <input

  	                    type="text"

  	                    bind:value={searchQuery}

  	                    placeholder="Search quality (e.g. 1080p)..."

  	                    class="h-12 w-full rounded-2xl bg-muted/50 pl-11 pr-4 text-sm font-bold focus:outline-none focus:ring-2 focus:ring-primary/20"

  	                    onpointerdown={(e) => e.stopPropagation()}

  	                    onkeydown={(e) => e.stopPropagation()}

  	                  />

  	                </div>

  	              </div>

  	              <div class="max-h-[350px] overflow-y-auto pr-1">

  	                <Select.Item

  	                  value=""

  	                  class="rounded-2xl py-4 px-5 font-bold transition-all focus:bg-primary focus:text-primary-foreground mb-1"

  	                >

  	                  <div class="flex items-center justify-between w-full">

  	                    <div class="flex flex-col gap-0.5">

  	                      <span class="text-base">Best Quality</span>

  	                      <span

  	                        class="text-[10px] opacity-70 font-medium tracking-wide uppercase"

  	                        >Automatic Selection</span

  	                      >

  	                    </div>

  	                    <div class="text-right">

  	                      <span

  	                        class="text-xs font-black opacity-40 uppercase tracking-widest"

  	                        >Default</span

  	                      >

  	                    </div>

  	                  </div>

  	                </Select.Item>

  	                {#if filteredOptions.length > 0}

  	                  {#each filteredOptions as option}

  	                    <Select.Item

  	                      value={option.format_id || ""}

  	                      class="rounded-2xl py-4 px-5 font-bold transition-all focus:bg-primary focus:text-primary-foreground mb-1 last:mb-0"

  	                    >

  	                      <div class="flex items-center justify-between w-full">

  	                        <div class="flex flex-col gap-0.5">

  	                          <span class="text-base"

  	                            >{option.resolution} •

  	                            <span class="uppercase opacity-60 text-xs"

  	                              >{option.extension}</span

  	                            ></span

  	                          >

  	                          <span

  	                            class="text-[10px] opacity-70 font-medium tracking-wide uppercase"

  	                            >{option.note || "Standard"}</span

  	                          >

  	                        </div>

  	                        <div class="text-right">

  	                          <span class="text-sm font-black tabular-nums"

  	                            >{formatFileSize(option.file_size)}</span

  	                          >

  	                        </div>

  	                      </div>

  	                    </Select.Item>

  	                  {/each}

  	                {:else}

  	                  <div class="py-12 text-center text-muted-foreground">

  	                    <FileVideo class="mx-auto h-8 w-8 opacity-20 mb-3" />

  	                    <p class="text-sm font-bold">No formats found</p>

  	                  </div>

  	                {/if}

  	              </div>

  	            </Select.Content>

  	          </Select.Root>

  	          <div class="flex items-center justify-between px-2 pt-6 border-t border-muted">
                <div class="space-y-0.5">
                  <Label class="text-lg font-bold">Re-encode to H.264</Label>
                  <p class="text-sm text-muted-foreground font-medium">
                    Ensures compatibility but takes longer
                  </p>
                </div>
                <Switch bind:checked={reEncode} aria-label="Toggle re-encoding" />
              </div>
  	        </div>

  	      </div>

  	    </div>

  	

  	    <div

  	      class="space-y-6 animate-in slide-in-from-top-4 duration-500 delay-150"

  	    >

  	      <div

  	        class="relative overflow-hidden rounded-[2.5rem] border bg-card p-2 shadow-2xl shadow-primary/5 transition-all focus-within:ring-2 focus-within:ring-primary/20"

  	      >

  	        <div class="relative">

  	          <Type

  	            class="absolute left-6 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground"

  	          />

  	          <input

  	            type="text"

  	            bind:value={customName}

  	            placeholder="Video Name (Optional)"

  	            class="h-16 w-full rounded-[2rem] border-none bg-transparent pl-14 pr-14 text-lg font-medium focus:outline-none focus:ring-0"

  	            disabled={loading}

  	          />

              {#if customName}
                <button
                  onclick={() => customName = ""}
                  class="absolute right-6 top-1/2 -translate-y-1/2 rounded-full p-2 hover:bg-muted transition-colors"
                  aria-label="Clear name"
                >
                  <X class="h-5 w-5 text-muted-foreground" />
                </button>
              {/if}

  	        </div>

  	      </div>

  	

  	      <Button.Root

  	        onclick={startDownload}

  	        disabled={loading || !url}

  	        class="h-20 w-full rounded-[2.5rem] text-2xl font-black shadow-2xl shadow-primary/20 transition-all hover:scale-[1.01] active:scale-[0.99]"

  	      >

  	        <Download class="mr-3 h-8 w-8 stroke-[3px]" />

  	        Start Download

  	      </Button.Root>

  	    </div>

  	  {/if}
</div>

// src/frontend/src/routes/download.tsx
import { useQueryClient } from "@tanstack/react-query";
import { getRouteApi, useNavigate } from "@tanstack/react-router";
import { Apple, ClipboardPaste, Download, Info, Loader2, Sparkles, Zap } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { z } from "zod";
import type { EncodingRequest, ServicesVideoMetadata, ServicesVideoOption } from "@/api/gen/model";
import { useGetSettings } from "@/api/gen/settings/settings";
import { useCreateVideo, useGetMetadata, useQuickDownload } from "@/api/gen/videos/videos";
import { EncodingEditor } from "@/components/encoding-editor";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { codecName, formatBytes, formatDuration } from "@/lib/format";
import { extractUrl } from "@/lib/url";
import { cn } from "@/lib/utils";
import { upsertVideo } from "@/lib/videos";

const route = getRouteApi("/app/download");
const urlSchema = z.url({ protocol: /^https?$/, error: "Enter a valid http(s) link" });

export function DownloadPage() {
	const search = route.useSearch();
	const navigate = useNavigate();
	const qc = useQueryClient();
	const [url, setUrl] = useState(search.url ? extractUrl(search.url) : "");
	const [error, setError] = useState<string>();
	const metadata = useGetMetadata();
	const quick = useQuickDownload({
		mutation: {
			onSuccess: (video) => {
				upsertVideo(qc, video);
				toast.success("Download started");
				navigate({ to: "/" });
			},
		},
	});

	const autoStarted = useRef(false);
	useEffect(() => {
		if (autoStarted.current || !search.quick || !search.url) return;
		autoStarted.current = true;
		quick.mutate({ data: { url: search.url } });
	}, [search.quick, search.url, quick]);

	const validate = () => {
		const clean = extractUrl(url);
		setUrl(clean);
		const parsed = urlSchema.safeParse(clean);
		setError(parsed.success ? undefined : parsed.error.issues[0]?.message);
		return parsed.success ? parsed.data : undefined;
	};

	const paste = async () => {
		try {
			const text = extractUrl(await navigator.clipboard.readText());
			setUrl(text);
			setError(undefined);
			metadata.reset();
		} catch {
			toast.error("Clipboard access was blocked");
		}
	};

	return (
		<div className="space-y-8">
			<div>
				<h1 className="font-extrabold text-4xl tracking-tight">Download</h1>
				<p className="mt-1 font-medium text-lg text-muted-foreground">
					Paste a link from YouTube, TikTok, Instagram and more.
				</p>
			</div>

			<form
				className="space-y-4 rounded-[2.5rem] border bg-card p-6"
				onSubmit={(e) => {
					e.preventDefault();
					const valid = validate();
					if (valid) quick.mutate({ data: { url: valid } });
				}}
			>
				<div className="space-y-2">
					<div className="flex gap-2">
						<Input
							type="url"
							inputMode="url"
							autoComplete="off"
							placeholder="https://…"
							value={url}
							aria-invalid={Boolean(error)}
							onPaste={(e) => {
								e.preventDefault();
								setUrl(extractUrl(e.clipboardData.getData("text")));
								setError(undefined);
								metadata.reset();
							}}
							onChange={(e) => {
								setUrl(e.target.value);
								setError(undefined);
								metadata.reset();
							}}
							className="h-12 rounded-2xl"
						/>
						<Button
							type="button"
							variant="secondary"
							size="icon"
							className="size-12 shrink-0 rounded-2xl"
							aria-label="Paste"
							onClick={paste}
						>
							<ClipboardPaste className="size-5" />
						</Button>
					</div>
					{error && <p className="px-1 font-medium text-destructive text-sm">{error}</p>}
				</div>
				<div className="grid gap-2 sm:grid-cols-2">
					<Button
						type="submit"
						size="lg"
						className="h-12 rounded-2xl font-bold text-base"
						disabled={quick.isPending}
					>
						{quick.isPending ? <Loader2 className="animate-spin" /> : <Zap />}
						Quick download
					</Button>
					<Button
						type="button"
						variant="secondary"
						size="lg"
						className="h-12 rounded-2xl font-bold text-base"
						disabled={metadata.isPending}
						onClick={() => {
							const valid = validate();
							if (valid) metadata.mutate({ data: { url: valid } });
						}}
					>
						{metadata.isPending ? <Loader2 className="animate-spin" /> : <Info />}
						Fetch info
					</Button>
				</div>
			</form>

			{metadata.isPending && <MetadataSkeleton />}
			{metadata.data && <FormatPicker key={url} url={extractUrl(url)} meta={metadata.data} />}
		</div>
	);
}

function MetadataSkeleton() {
	return (
		<div className="space-y-6 rounded-[2.5rem] border bg-card p-6">
			<div className="flex gap-4">
				<Skeleton className="aspect-video w-36 shrink-0 rounded-2xl" />
				<div className="flex-1 space-y-2 pt-1">
					<Skeleton className="h-5 w-full rounded-md" />
					<Skeleton className="h-5 w-2/3 rounded-md" />
					<Skeleton className="h-4 w-1/3 rounded-md" />
				</div>
			</div>
			<Skeleton className="h-11 w-full rounded-xl" />
			<div className="space-y-2">
				<Skeleton className="h-16 w-full rounded-2xl" />
				<Skeleton className="h-16 w-full rounded-2xl" />
				<Skeleton className="h-16 w-full rounded-2xl" />
			</div>
		</div>
	);
}

function FormatPicker({ url, meta }: { url: string; meta: ServicesVideoMetadata }) {
	const navigate = useNavigate();
	const qc = useQueryClient();
	const settings = useGetSettings();
	const [name, setName] = useState(meta.title);
	const [formatId, setFormatId] = useState<string>();
	const [encoding, setEncoding] = useState<EncodingRequest>();
	const option = meta.options.find((o) => o.formatId === formatId);
	const value = encoding ?? settings.data?.defaultEncoding ?? { goal: "original" };

	const create = useCreateVideo({
		mutation: {
			onSuccess: (video) => {
				upsertVideo(qc, video);
				toast.success("Download started");
				navigate({ to: "/" });
			},
		},
	});

	return (
		<div className="space-y-6 rounded-[2.5rem] border bg-card p-6">
			<div className="flex gap-4">
				{meta.thumbnail ? (
					<img
						src={meta.thumbnail}
						alt=""
						referrerPolicy="no-referrer"
						className="aspect-video w-36 shrink-0 rounded-2xl bg-muted object-cover"
					/>
				) : (
					<Skeleton className="aspect-video w-36 shrink-0 animate-none rounded-2xl" />
				)}
				<div className="min-w-0">
					<p className="line-clamp-2 font-bold leading-snug">{meta.title}</p>
					<p className="mt-1 text-muted-foreground text-sm">
						{[meta.uploader, formatDuration(meta.duration), meta.extractor].filter(Boolean).join(" · ")}
					</p>
				</div>
			</div>

			<div className="space-y-2">
				<Label htmlFor="name" className="font-semibold">
					Name
				</Label>
				<Input id="name" value={name} onChange={(e) => setName(e.target.value)} maxLength={255} />
			</div>

			<div className="space-y-2">
				<Label className="font-semibold">Format</Label>
				<div className="max-h-80 space-y-2 overflow-y-auto overscroll-contain">
					<FormatOption selected={!formatId} onSelect={() => setFormatId(undefined)}>
						<span className="flex items-center gap-2 font-bold">
							<Sparkles className="size-4" /> Best available
						</span>
						<span className="text-muted-foreground text-sm">Highest quality video and audio</span>
					</FormatOption>
					{meta.options.map((o) => (
						<FormatOption
							key={o.formatId}
							selected={formatId === o.formatId}
							onSelect={() => setFormatId(o.formatId)}
						>
							<OptionLabel option={o} />
						</FormatOption>
					))}
				</div>
			</div>

			<div className="space-y-2">
				<Label className="font-semibold">Encoding</Label>
				{settings.data ? (
					<EncodingEditor
						value={value}
						onChange={setEncoding}
						source={option ? toSource(option, meta) : undefined}
					/>
				) : (
					<Skeleton className="h-40 w-full rounded-2xl" />
				)}
			</div>

			<Button
				size="lg"
				className="h-12 w-full rounded-2xl font-bold text-base"
				disabled={create.isPending || !name.trim()}
				onClick={() =>
					create.mutate({
						data: { url, name: name.trim(), sourceTitle: meta.title, formatId, encoding: value },
					})
				}
			>
				{create.isPending ? <Loader2 className="animate-spin" /> : <Download />}
				Download
			</Button>
		</div>
	);
}

function FormatOption({
	selected,
	onSelect,
	children,
}: {
	selected: boolean;
	onSelect: () => void;
	children: React.ReactNode;
}) {
	return (
		<button
			type="button"
			onClick={onSelect}
			className={cn(
				"flex w-full flex-col items-start gap-0.5 rounded-2xl border-2 px-4 py-3 text-left transition-colors",
				selected ? "border-primary bg-primary/5" : "border-transparent bg-muted/60 hover:bg-muted",
			)}
		>
			{children}
		</button>
	);
}

function OptionLabel({ option: o }: { option: ServicesVideoOption }) {
	return (
		<>
			<span className="flex flex-wrap items-center gap-2 font-bold">
				{o.resolution}
				{o.fps ? <span className="font-medium text-muted-foreground">{Math.round(o.fps)}fps</span> : null}
				{o.iosCompatible && (
					<Badge variant="secondary" className="rounded-full">
						<Apple /> iPhone
					</Badge>
				)}
				{o.dynamicRange && o.dynamicRange !== "SDR" && (
					<Badge variant="secondary" className="rounded-full">
						{o.dynamicRange}
					</Badge>
				)}
			</span>
			<span className="text-muted-foreground text-sm">
				{[
					codecName(o.videoCodec),
					o.hasAudio ? codecName(o.audioCodec) : "no audio",
					o.extension.toUpperCase(),
					formatBytes(o.fileSize),
					o.note,
				]
					.filter(Boolean)
					.join(" · ")}
			</span>
		</>
	);
}

function toSource(o: ServicesVideoOption, meta: ServicesVideoMetadata) {
	return {
		videoCodec: o.videoCodec,
		audioCodec: o.audioCodec,
		container: o.extension,
		width: o.width ?? 0,
		height: o.height ?? 0,
		fps: o.fps ?? 0,
		bitrate: Math.round((o.bitrate ?? 0) * 1000),
		duration: meta.duration,
	};
}
