// frontend/src/lib/components/video-card.svelte
<script lang="ts">
  import type {
    HandlersVideoResponse,
    ServicesDownloadProgressDTO,
  } from "$api/index";
  import * as Button from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import { Progress } from "$lib/components/ui/progress/index.js";
  import {
    Trash2,
    Play,
    ExternalLink,
    Clock,
    Download,
    HardDrive,
    Copy,
    Check,
    Pencil,
    X,
    Save,
  } from "@lucide/svelte";

  let {
    video,
    progress,
    isPlaying,
    copiedId,
    editingId,
    editingName = $bindable(""),
    onTogglePlay,
    onStartEditing,
    onCancelEditing,
    onRename,
    onDelete,
    onCopyId,
  }: {
    video: HandlersVideoResponse;
    progress: ServicesDownloadProgressDTO | undefined;
    isPlaying: boolean;
    copiedId: string | null;
    editingId: string | null;
    editingName: string;
    onTogglePlay: (id: string) => void;
    onStartEditing: (video: HandlersVideoResponse) => void;
    onCancelEditing: () => void;
    onRename: (id: string) => void;
    onDelete: (id: string) => void;
    onCopyId: (text: string, id: string) => void;
  } = $props();

  const currentStatus = $derived(
    progress?.status || video.downloadStatus || "unknown",
  );
  const isProcessing = $derived(
    ["downloading", "encoding", "pending"].includes(currentStatus.toLowerCase()),
  );
  const isCompleted = $derived(currentStatus.toLowerCase() === "completed");
  const isEditing = $derived(editingId === video.id);

  function getStatusColor(status: string) {
    switch (status.toLowerCase()) {
      case "completed":
        return "bg-green-500/10 text-green-500 border-green-500/20";
      case "downloading":
        return "bg-blue-500/10 text-blue-500 border-blue-500/20";
      case "encoding":
        return "bg-yellow-500/10 text-yellow-500 border-yellow-500/20";
      case "error":
        return "bg-red-500/10 text-red-500 border-red-500/20";
      default:
        return "bg-slate-500/10 text-slate-500 border-slate-500/20";
    }
  }
</script>

<div
  class="group relative flex flex-col overflow-hidden rounded-[2rem] border bg-card transition-all hover:shadow-2xl hover:shadow-primary/5"
>
  {#if isPlaying && isCompleted}
    <div class="aspect-video w-full overflow-hidden bg-black">
      <!-- svelte-ignore a11y_media_has_caption -->
      <video
        src={`/downloads/${video.fileName}`}
        controls
        autoplay
        playsinline
        preload="metadata"
        class="h-full w-full object-contain"
      >
      </video>
    </div>
  {:else}
    <button
      class="relative aspect-video w-full overflow-hidden bg-black transition-all hover:cursor-pointer"
      onclick={() => isCompleted && video.id && onTogglePlay(video.id)}
      disabled={!isCompleted}
    >
      {#if video.thumbnailFileName}
        <img
          src={`/downloads/${video.thumbnailFileName}`}
          alt={video.name}
          class="h-full w-full object-contain transition-transform duration-700 group-hover:scale-110"
        />
      {:else}
        <div
          class="flex h-full items-center justify-center text-muted-foreground"
        >
          <HardDrive class="h-12 w-12 opacity-20" />
        </div>
      {/if}

      <div class="absolute top-4 right-4">
        <Badge
          variant="outline"
          class={`px-3 py-1 rounded-full border-none font-bold backdrop-blur-md ${getStatusColor(currentStatus)}`}
        >
          {currentStatus.toUpperCase()}
        </Badge>
      </div>

      {#if isCompleted}
        <div
          class="absolute inset-0 flex items-center justify-center bg-black/20 opacity-0 [@media(hover:none)]:opacity-100 [@media(hover:none)]:bg-black/40 transition-all duration-300 group-hover:bg-black/40 group-hover:opacity-100"
        >
          <div
            class="rounded-full bg-white p-5 text-black shadow-2xl transition-transform duration-300 hover:scale-110 active:scale-90"
          >
            <Play class="h-8 w-8 fill-current" />
          </div>
        </div>
      {/if}
    </button>
  {/if}

  <div class="flex flex-1 flex-col p-6 sm:p-8 min-w-0">
    <div class="flex items-start justify-between gap-6">
      <div class="space-y-1 min-w-0 flex-1">
        {#if isEditing}
          <div class="flex items-center gap-2">
            <Input
              bind:value={editingName}
              class="h-10 rounded-lg bg-muted/50 border-primary/20 focus-visible:ring-primary/20"
              autofocus
              onkeydown={(e) => {
                if (e.key === "Enter") onRename(video.id!);
                if (e.key === "Escape") onCancelEditing();
              }}
            />
            <Button.Root
              variant="ghost"
              size="icon"
              onclick={() => onRename(video.id!)}
              class="h-10 w-10 shrink-0 text-green-600 hover:bg-green-500/10 hover:cursor-pointer"
            >
              <Save class="h-5 w-5" />
            </Button.Root>
            <Button.Root
              variant="ghost"
              size="icon"
              onclick={onCancelEditing}
              class="h-10 w-10 shrink-0 text-muted-foreground hover:bg-muted hover:cursor-pointer"
            >
              <X class="h-5 w-5" />
            </Button.Root>
          </div>
        {:else}
          <h3
            class="text-xl font-bold leading-tight tracking-tight sm:text-2xl line-clamp-2"
            title={video.name}
          >
            {video.name || "Untitled Video"}
          </h3>
        {/if}

        {#if video.id}
          <button
            onclick={() => onCopyId(video.id!, video.id!)}
            class="flex items-center gap-1.5 text-xs font-mono text-muted-foreground hover:text-primary transition-colors group/guid"
          >
            <span class="truncate max-w-[150px]">{video.id}</span>
            {#if copiedId === video.id}
              <Check class="h-3 w-3 text-green-500" />
            {:else}
              <Copy class="h-3 w-3 opacity-0 group-hover/guid:opacity-100" />
            {/if}
          </button>
        {/if}
      </div>
      <div class="grid grid-cols-2 gap-2 shrink-0">
        {#if !isEditing}
          <Button.Root
            variant="secondary"
            size="icon"
            onclick={() => onStartEditing(video)}
            class="h-11 w-11 rounded-2xl hover:cursor-pointer"
          >
            <Pencil class="h-5 w-5" />
          </Button.Root>
        {/if}
        {#if isCompleted}
          <Button.Root
            variant="secondary"
            size="icon"
            onclick={() => window.open(`/downloads/${video.fileName}`, "_blank")}
            class="h-11 w-11 rounded-2xl hover:cursor-pointer"
          >
            <ExternalLink class="h-5 w-5" />
          </Button.Root>
          <Button.Root
            variant="secondary"
            size="icon"
            href={`/downloads/${video.fileName}`}
            download={video.fileName}
            disabled={video.downloadStatus !== "completed"}
            class="h-11 w-11 rounded-2xl hover:cursor-pointer"
          >
            <Download class="h-5 w-5" />
          </Button.Root>
        {/if}
        <Button.Root
          variant="secondary"
          size="icon"
          onclick={() => video.id && onDelete(video.id)}
          class="h-11 w-11 rounded-2xl text-destructive hover:bg-destructive/10 hover:text-destructive hover:cursor-pointer"
        >
          <Trash2 class="h-5 w-5" />
        </Button.Root>
      </div>
    </div>

    <div class="mt-6">
      {#if isProcessing}
        <div class="space-y-3">
          <div class="flex items-center justify-between text-sm font-bold">
            <span class="flex items-center gap-2">
              {#if currentStatus.toLowerCase() === "encoding"}
                <div class="relative flex h-3 w-3">
                  <span
                    class="absolute inline-flex h-full w-full animate-ping rounded-full bg-yellow-400 opacity-75"
                  ></span>
                  <span
                    class="relative inline-flex h-3 w-3 rounded-full bg-yellow-500"
                  ></span>
                </div>
                <span
                  class="text-yellow-600 dark:text-yellow-500 uppercase tracking-wider text-xs"
                  >Encoding...</span
                >
              {:else}
                <div class="relative flex h-3 w-3">
                  <span
                    class="absolute inline-flex h-full w-full animate-ping rounded-full bg-blue-400 opacity-75"
                  ></span>
                  <span
                    class="relative inline-flex h-3 w-3 rounded-full bg-blue-500"
                  ></span>
                </div>
                <span
                  class="text-blue-600 dark:text-blue-500 uppercase tracking-wider text-xs"
                  >{progress?.speed || "Downloading..."}</span
                >
              {/if}
            </span>
            <span class="text-lg tabular-nums">
              {(currentStatus.toLowerCase() === "encoding"
                ? progress?.encodingPercent
                : progress?.percent
              )?.toFixed(0) || 0}%
            </span>
          </div>
          <Progress
            value={(currentStatus.toLowerCase() === "encoding"
              ? progress?.encodingPercent
              : progress?.percent) || 0}
            class="h-3 rounded-full"
          />
          {#if progress?.eta}
            <p class="text-right text-xs font-medium text-muted-foreground">
              ETA: {progress.eta}
            </p>
          {/if}
        </div>
      {:else}
        <div
          class="flex items-center gap-2 text-sm font-medium text-muted-foreground"
        >
          <Clock class="h-4 w-4" />
          <span
            >Added {new Date(video.createdAt || "").toLocaleDateString(
              undefined,
              { month: "short", day: "numeric", year: "numeric" },
            )}</span
          >
        </div>
      {/if}
    </div>
  </div>
</div>

// src/frontend/src/components/video-card.tsx
import { useQueryClient } from "@tanstack/react-query";
import {
	Apple,
	Check,
	Copy,
	Download,
	Ellipsis,
	ExternalLink,
	Film,
	Layers,
	Link2,
	Loader2,
	Pencil,
	Play,
	Share,
	Trash2,
	Type,
	Wand2,
	X,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useCreateVersion } from "@/api/gen/versions/versions";
import { useDeleteVideo, useUpdateVideo } from "@/api/gen/videos/videos";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { EncodeSheet } from "@/components/encode-sheet";
import { JobProgress } from "@/components/job-progress";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { VersionsSheet } from "@/components/versions-sheet";
import { formatDuration, randomNamePattern } from "@/lib/format";
import { canSaveToPhotos, downloadUrl, useSaveToPhotos } from "@/lib/save";
import { cn } from "@/lib/utils";
import {
	activeStatuses,
	primaryFile,
	removeVideo,
	upsertVideo,
	useVideoProgress,
	type Video,
	type VideoFile,
} from "@/lib/videos";

const statusStyles: Record<string, string> = {
	queued: "bg-muted/90 text-foreground",
	downloading: "bg-blue-500/90 text-white",
	encoding: "bg-violet-500/90 text-white",
	error: "bg-destructive/90 text-white",
	canceled: "bg-muted/90 text-foreground",
};

export function VideoCard({ video }: { video: Video }) {
	const [playing, setPlaying] = useState(false);
	const [versionsOpen, setVersionsOpen] = useState(false);
	const [encode, setEncode] = useState<{ open: boolean; source?: string; key: number }>({
		open: false,
		key: 0,
	});
	const [confirmDelete, setConfirmDelete] = useState(false);
	const [renaming, setRenaming] = useState(false);
	const progress = useVideoProgress(video.id);
	const qc = useQueryClient();

	const primary = primaryFile(video);
	const ready = primary?.status === "completed";
	const active = video.files.filter((f) => activeStatuses.has(f.status));
	const completedCount = video.files.filter((f) => f.status === "completed").length;

	const remove = useDeleteVideo({
		mutation: {
			onMutate: () => removeVideo(qc, video.id),
			onSuccess: () => toast.success("Video deleted"),
			onError: () => qc.invalidateQueries({ queryKey: ["/api/videos"] }),
		},
	});

	const openEncode = (source?: string) => {
		setVersionsOpen(false);
		setEncode((e) => ({ open: true, source, key: e.key + 1 }));
	};

	const copy = async (text: string, what: string) => {
		await navigator.clipboard.writeText(text);
		toast.success(`${what} copied`);
	};

	return (
		<article className="group overflow-hidden rounded-[2.5rem] border bg-card transition-shadow hover:shadow-2xl hover:shadow-primary/5">
			<div className="relative aspect-video w-full overflow-hidden bg-muted">
				{playing && primary?.url ? (
					// biome-ignore lint/a11y/useMediaCaption: user videos have no captions
					<video
						src={primary.url}
						controls
						autoPlay
						playsInline
						className="size-full bg-black object-contain"
					/>
				) : (
					<button
						type="button"
						className="relative block size-full disabled:cursor-default"
						onClick={() => setPlaying(true)}
						disabled={!ready}
						aria-label="Play"
					>
						<Thumbnail video={video} />
						<div className="absolute top-4 right-4 left-4 flex items-start justify-between gap-2">
							<span />
							{video.status !== "completed" && (
								<Badge
									className={cn(
										"rounded-full border-none px-3 py-1 font-bold uppercase backdrop-blur-md",
										statusStyles[video.status],
									)}
								>
									{video.status}
								</Badge>
							)}
						</div>
						{video.duration ? (
							<span className="absolute right-4 bottom-4 rounded-lg bg-black/70 px-2 py-0.5 font-bold text-white text-xs tabular-nums">
								{formatDuration(video.duration)}
							</span>
						) : null}
						{ready && (
							<span className="absolute inset-0 flex items-center justify-center bg-black/0 transition-colors group-hover:bg-black/30 [@media(hover:none)]:bg-black/20">
								<span className="rounded-full bg-white p-4 text-black opacity-0 shadow-2xl transition-all group-hover:opacity-100 [@media(hover:none)]:opacity-100">
									<Play className="size-7 fill-current" />
								</span>
							</span>
						)}
					</button>
				)}
				{completedCount > 1 && !playing && (
					<button
						type="button"
						onClick={() => setVersionsOpen(true)}
						className="absolute top-4 left-4 inline-flex items-center gap-1.5 rounded-full bg-black/60 px-3 py-1 font-bold text-white text-xs backdrop-blur-md transition-colors hover:bg-black/75"
					>
						<Layers className="size-3.5" /> {completedCount} versions
					</button>
				)}
			</div>

			<div className="space-y-5 p-6">
				<div className="min-w-0 space-y-1.5">
					{renaming ? (
						<RenameField video={video} onDone={() => setRenaming(false)} />
					) : (
						<div className="flex items-start gap-2">
							<h3
								className="line-clamp-2 min-w-0 flex-1 font-bold text-xl leading-tight tracking-tight"
								title={video.name}
							>
								{video.name}
							</h3>
							<Button
								variant="ghost"
								size="icon"
								className="-mt-1 size-8 shrink-0 rounded-lg text-muted-foreground"
								aria-label="Rename"
								onClick={() => setRenaming(true)}
							>
								<Pencil />
							</Button>
						</div>
					)}
					<div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 text-muted-foreground text-xs">
						{video.uploader && <span className="font-medium">{video.uploader}</span>}
						<button
							type="button"
							onClick={() => copy(video.id, "ID")}
							className="max-w-40 truncate font-mono transition-colors hover:text-foreground"
						>
							{video.id}
						</button>
					</div>
					{!renaming &&
						video.sourceTitle &&
						video.sourceTitle !== video.name &&
						randomNamePattern.test(video.name) && <UseSourceTitle video={video} />}
				</div>

				{active.length > 0 && (
					<div className="space-y-3">
						{active.map((f) => (
							<JobProgress key={f.id} file={f} progress={progress?.find((p) => p.fileId === f.id)} />
						))}
					</div>
				)}

				<div className="flex gap-2">
					<PrimaryAction video={video} file={ready ? primary : undefined} status={video.status} />
					<Button
						variant="secondary"
						size="icon"
						className="size-12 shrink-0 rounded-2xl"
						aria-label="Re-encode"
						disabled={completedCount === 0}
						onClick={() => openEncode()}
					>
						<Wand2 className="size-5" />
					</Button>
					<DropdownMenu>
						<DropdownMenuTrigger asChild>
							<Button
								variant="secondary"
								size="icon"
								className="size-12 shrink-0 rounded-2xl"
								aria-label="More"
							>
								<Ellipsis className="size-5" />
							</Button>
						</DropdownMenuTrigger>
						<DropdownMenuContent align="end" className="w-56 rounded-2xl p-1.5">
							<DropdownMenuItem onSelect={() => setRenaming(true)}>
								<Pencil /> Rename
							</DropdownMenuItem>
							<DropdownMenuItem onSelect={() => setVersionsOpen(true)}>
								<Layers /> Versions…
							</DropdownMenuItem>
							{ready && (
								<DropdownMenuItem asChild>
									<a href={primary.url} target="_blank" rel="noreferrer">
										<ExternalLink /> Open in new tab
									</a>
								</DropdownMenuItem>
							)}
							{ready && canSaveToPhotos && (
								<DropdownMenuItem asChild>
									<a href={downloadUrl(primary)} download>
										<Download /> Download file
									</a>
								</DropdownMenuItem>
							)}
							<DropdownMenuItem onSelect={() => copy(video.originalUrl, "Source URL")}>
								<Link2 /> Copy source URL
							</DropdownMenuItem>
							<DropdownMenuItem onSelect={() => copy(video.id, "ID")}>
								<Copy /> Copy ID
							</DropdownMenuItem>
							<DropdownMenuSeparator />
							<DropdownMenuItem variant="destructive" onSelect={() => setConfirmDelete(true)}>
								<Trash2 /> Delete video
							</DropdownMenuItem>
						</DropdownMenuContent>
					</DropdownMenu>
				</div>
			</div>

			<VersionsSheet
				video={video}
				open={versionsOpen}
				onOpenChange={setVersionsOpen}
				onReencode={openEncode}
			/>
			<EncodeSheet
				key={encode.key}
				video={video}
				open={encode.open}
				sourceFileId={encode.source}
				onOpenChange={(open) => setEncode((e) => ({ ...e, open }))}
			/>
			<ConfirmDialog
				open={confirmDelete}
				onOpenChange={setConfirmDelete}
				title="Delete this video?"
				description={`"${video.name}" and all of its versions will be removed from disk.`}
				action="Delete"
				onConfirm={() => remove.mutate({ id: video.id })}
			/>
		</article>
	);
}

function Thumbnail({ video }: { video: Video }) {
	const [loaded, setLoaded] = useState(false);
	if (!video.thumbnailUrl) {
		return (
			<span className="flex size-full items-center justify-center text-muted-foreground">
				<Film className="size-12 opacity-30" />
			</span>
		);
	}
	return (
		<img
			src={video.thumbnailUrl}
			alt=""
			loading="lazy"
			decoding="async"
			onLoad={() => setLoaded(true)}
			className={cn(
				"size-full object-cover transition-[opacity,scale] duration-500 group-hover:scale-105",
				loaded ? "opacity-100" : "opacity-0",
			)}
		/>
	);
}

function RenameField({ video, onDone }: { video: Video; onDone: () => void }) {
	const qc = useQueryClient();
	const [name, setName] = useState(video.name);
	const update = useUpdateVideo({ mutation: { onSuccess: (v) => upsertVideo(qc, v) } });

	const save = () => {
		const trimmed = name.trim();
		if (trimmed && trimmed !== video.name) {
			upsertVideo(qc, { ...video, name: trimmed });
			update.mutate({ id: video.id, data: { name: trimmed } });
		}
		onDone();
	};

	return (
		<form
			className="flex items-center gap-2"
			onSubmit={(e) => {
				e.preventDefault();
				save();
			}}
		>
			<Input
				value={name}
				onChange={(e) => setName(e.target.value)}
				onKeyDown={(e) => e.key === "Escape" && onDone()}
				autoFocus
				maxLength={255}
				className="font-semibold"
			/>
			<Button
				type="submit"
				variant="secondary"
				size="icon"
				className="size-11 shrink-0 rounded-xl"
				aria-label="Save"
			>
				<Check />
			</Button>
			<Button
				type="button"
				variant="ghost"
				size="icon"
				className="size-11 shrink-0 rounded-xl"
				aria-label="Cancel"
				onClick={onDone}
			>
				<X />
			</Button>
		</form>
	);
}

function UseSourceTitle({ video }: { video: Video }) {
	const qc = useQueryClient();
	const update = useUpdateVideo({ mutation: { onSuccess: (v) => upsertVideo(qc, v) } });
	const title = video.sourceTitle ?? "";
	return (
		<button
			type="button"
			onClick={() => {
				upsertVideo(qc, { ...video, name: title });
				update.mutate({ id: video.id, data: { name: title } });
			}}
			className="mt-1 inline-flex max-w-full items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 font-semibold text-xs transition-colors hover:bg-muted/70"
		>
			<Type className="size-3.5 shrink-0" />
			<span className="truncate">Use “{title}”</span>
		</button>
	);
}

function PrimaryAction({ video, file, status }: { video: Video; file?: VideoFile; status: string }) {
	const qc = useQueryClient();
	const save = useSaveToPhotos(video.name, file);
	const makeCompatible = useCreateVersion({
		mutation: {
			onSuccess: () => {
				qc.invalidateQueries({ queryKey: ["/api/videos"] });
				toast.success("Making an iPhone version");
			},
		},
	});
	const base = "h-12 flex-1 rounded-2xl font-bold text-base";

	if (!file) {
		return (
			<Button className={base} disabled>
				{activeStatuses.has(status) ? <Loader2 className="animate-spin" /> : <Download />}
				{activeStatuses.has(status) ? "Preparing…" : "Unavailable"}
			</Button>
		);
	}

	if (!canSaveToPhotos) {
		return (
			<Button asChild className={base}>
				<a href={downloadUrl(file)} download>
					<Download /> Download
				</a>
			</Button>
		);
	}

	if (!file.iosCompatible) {
		return (
			<Button
				className={base}
				disabled={makeCompatible.isPending}
				onClick={() =>
					makeCompatible.mutate({
						id: video.id,
						data: { sourceFileId: file.id, encoding: { goal: "compatible" }, makePrimary: true },
					})
				}
			>
				<Apple /> Make iPhone version
			</Button>
		);
	}

	switch (save.state.kind) {
		case "fetching":
			return (
				<Button className={cn(base, "relative overflow-hidden")} variant="secondary" onClick={save.cancel}>
					<span
						className="absolute inset-y-0 left-0 bg-primary/15 transition-[width]"
						style={{ width: `${Math.round(save.state.progress * 100)}%` }}
					/>
					<Loader2 className="animate-spin" />
					<span className="tabular-nums">Preparing {Math.round(save.state.progress * 100)}%</span>
				</Button>
			);
		case "ready":
			return (
				<Button className={base} onClick={save.share}>
					<Share /> Tap to save
				</Button>
			);
		default:
			return (
				<Button className={base} onClick={save.prepare}>
					<Download /> Save to Photos
				</Button>
			);
	}
}
